// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int times = Integer.parseInt(args[0]);
		int big = 0;
		int small = 0;
		for (int i=0; i<times; i++){
			double flip = Math.random();
			if (flip>0.5){
				big+=1;
			}else{
				small+=1;
			}
		}if (small==0||big==0){
			System.out.println("> 0.5:" + big + " times");
			System.out.println("<= 0.5: " + small + " times");

		}else{
		double ratio = (double)small/big;
		System.out.println("> 0.5: " + big + " times");
		System.out.println("<= 0.5: " + small + " times");
		System.out.println("ratio: " + ratio);
		}
	    // Replace this comment with your code
	}
}
